export const VisitorsActionConst = {
    DECREMENT_BLOG_VISITOR_COUNT: 'DECREMENT_BLOG_VISITOR_COUNT',
    INCREMENT_BLOG_VISITOR_COUNT: 'INCREMENT_BLOG_VISITOR_COUNT',
    RESET_BLOG_VISITOR_COUNT: 'RESET_BLOG_VISITOR_COUNT',
};
 